version: '3.8'

services:
  php:
    build: .
    container_name: php
    volumes:
      - ./app:/var/www
    depends_on:
      - database

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8585:80"
    volumes:
      - ./app:/var/www
      - ./app/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: user
      PMA_PASSWORD: 1234
    ports:
      - "8586:80"
  database:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3388:3306"
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d